version: "3.9"

services:
  web:
    image: "camilochaves/alpineelixir:v1.0"
    restart: always
    tty: true
    ports:
      - "4000:4000"
  db:
    image: "camilochaves/alpinepostgresql:v1.0"
    restart: always
    tty: true
    ports:
      - "5432:5432"
    environment: 
      - "POSTGRES_USER=camilochaves"
      - "POSTGRES_PASSWORD=123camilo"
      - "POSTGRES_DB=TCPO"
    volumes:
      -  db-data:/var/lib/postgresql/data
    
  pgAdmin:
    image: "dpage/pgadmin4"
    restart: always
    tty: true    
    ports: 
      - 5050:80 
    environment: 
      - "PGADMIN_DEFAULT_EMAIL=chaves.camilo@gmail.com"
      - "PGADMIN_DEFAULT_PASSWORD=123camilo"
      - "PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True"
      - "PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10"  
      - "PGDATA=/var/lib/pgadmin"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:
